#!/usr/bin/env python3

import sys
import socket
import argparse


parser = argparse.ArgumentParser(description='Control Audio Switcher')

parser.add_argument('action', choices=['on', 'off', 'state'],
                    help='Action for switcher-server to take')
parser.add_argument('--host', dest='host', default='localhost',
                    help='Hostname or IP address of switcher-server')
parser.add_argument('--port', dest='port', type=int, default=5555,
                    help='TCP port of switcher-server')

args = parser.parse_args()

sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
sock.settimeout(4)

return_code = 0

try:

    sock.connect((args.host, args.port))

except (socket.timeout, ConnectionRefusedError):

    print("Unable to connect to switcher-server at {}:{}.".format(
        args.host, args.port), file=sys.stderr)
    sock.close()
    sys.exit(1)

if args.action == 'on':

    sock.sendall(b'1')

elif args.action == 'off':

    sock.sendall(b'0')

elif args.action == 'state':


    sock.sendall(b'S')
    state = sock.recv(1)

    if int(state) == 0:

        print('On')
        return_code = 1 # Some modules like homebridge-cmdswitch2 use return code for switch state.

    elif int(state) == 1:

        print('On')

    else:

        print("Unexpected state response from switcher-server at {}:{}: '{}'".format(
            args.host, args.port, state), file=sys.stderr)
        return_code = 2

sock.close()
sys.exit(return_code)
